services:
  postgres:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  summarization-postgres:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${SUMMARIZATION_POSTGRES_USER}
      POSTGRES_PASSWORD: ${SUMMARIZATION_POSTGRES_PASSWORD}
      POSTGRES_DB: ${SUMMARIZATION_POSTGRES_DB}
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - summarization_pgdata:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  rabbitmq:
    image: rabbitmq:4.2-management
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmq-diagnostics ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  redis:
    image: redis:8
    restart: unless-stopped
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    environment:
      REDISCLI_AUTH: ${REDIS_PASSWORD}
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 40s

  kafka:
    image: apache/kafka:4.3.1
    restart: unless-stopped
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: CONTROLLER://:29093,PLAINTEXT://:19092,PLAINTEXT_HOST://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:19092,PLAINTEXT_HOST://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      CLUSTER_ID: ${CLUSTER_ID}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    ports:
      - "127.0.0.1:9092:9092"
    volumes:
      - kafka_data:/var/lib/kafka/data
    healthcheck:
      test: [ "CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s


  backend:
    image: godmode13/task-tracker-backend:main
    restart: unless-stopped
    env_file:
      - ./backend.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      kafka:
        condition: service_healthy
      backend-migrations:
        condition: service_completed_successfully

  email-sender:
    image: godmode13/task-tracker-backend:main
    restart: unless-stopped
    env_file:
      - ./backend.env
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: celery -A app.celery_app worker --loglevel=info --queues=celery

  report-worker:
    image: godmode13/task-tracker-backend:main
    restart: unless-stopped
    env_file:
      - ./backend.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
      backend-migrations:
        condition: service_completed_successfully
    command: celery -A app.celery_app worker --loglevel=info --queues=reports

  scheduler:
    image: godmode13/task-tracker-backend:main
    restart: unless-stopped
    env_file:
      - ./backend.env
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: celery -A app.celery_app beat --loglevel=info --schedule /var/lib/celery/celerybeat-schedule
    volumes:
      - celerybeat_data:/var/lib/celery

  summarization-service:
    image: godmode13/summarization-service:main
    restart: unless-stopped
    env_file:
      - ./summarization.env
    depends_on:
      kafka:
        condition: service_healthy
      summarization-postgres:
        condition: service_healthy
      summarization-migrations:
        condition: service_completed_successfully

  frontend:
    image: godmode13/task-tracker-frontend:main
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_started

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    depends_on:
      - frontend

  backend-migrations:
    image: godmode13/task-tracker-backend:main
    restart: "no"
    env_file:
      - ./backend.env
    command: alembic upgrade head
    depends_on:
      postgres:
        condition: service_healthy

  summarization-migrations:
    image: godmode13/summarization-service:main
    restart: "no"
    env_file:
      - ./summarization.env
    command: alembic upgrade head
    depends_on:
      summarization-postgres:
        condition: service_healthy

volumes:
  pgdata:
  rabbitmq_data:
  redis_data:
  kafka_data:
  summarization_pgdata:
  celerybeat_data:
  caddy_data: